source "https://rubygems.org"


gem "karafka", ">= 2.4.0"
gem "waterdrop"
gem "rails", "~> 8.1.3"
gem "sprockets-rails"
gem "puma", ">= 5.0"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors", "~> 2.0.2"
gem "dotenv-rails", "~> 3.1.8"
gem "redis"
gem "httparty"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.0"
  gem "faker", "~> 2.0"
  gem "shoulda-matchers", "~> 5.0"
  gem "webmock", "~> 3.0"
  gem "vcr", "~> 6.0"
end

group :production do
  gem "rails_stdout_logging"
  gem "rack-attack"
end
