source "https://rubygems.org"


gem "rails", "~> 8.1.3"
gem "sprockets-rails"
gem "sqlite3", ">= 1.4"
gem "dotenv-rails"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "redis-session-store"
gem "karafka", ">= 2.4.0"
gem "sidekiq", "~> 7.0"
gem "net"
gem "redis"
gem "sidekiq-cron"
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development, :production do
  gem "mysql2"
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.0"
  gem "faker", "~> 2.0"
  gem "shoulda-matchers", "~> 5.0"
  gem "webmock", "~> 3.0"
  gem "vcr", "~> 6.0"
end
