services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    networks:
      - kafka_net
    volumes:
      - redis_data:/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - kafka_net
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=SuperSecure123

  zookeeper:
    image: ubuntu/zookeeper:3.8-22.04_edge
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_net
    # Образ ubuntu/zookeeper по умолчанию разрешает анонимный доступ
    # ALLOW_ANONYMOUS_LOGIN не требуется

  kafka:
    image: ubuntu/kafka:3.9.1-22.04_edge
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      # Основные переменные для ubuntu/kafka
      - ZOOKEEPER_HOST=zookeeper
      - ZOOKEEPER_PORT=2181
      # Для внешнего доступа используем порт 29092
      # Образ автоматически настроит слушателя на 0.0.0.0:9092
    networks:
      - kafka_net
    depends_on:
      - zookeeper

  # auth_service:
  #   build: ./auth_service
  #   ports:
  #     - '3001:3000'
  #   environment:
  #     - KAFKA_BROKERS=kafka:9092  # Внутренний адрес остается прежним
  #     - RAILS_ENV=development
  #   depends_on:
  #     - kafka
  #   volumes:
  #     - ./auth_service:/app
  #   networks:
  #     - kafka_net

  # web_service:
  #   build: ./web_service
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - KAFKA_BROKER=kafka:9092   # Внутренний адрес остается прежним
  #     - RAILS_ENV=development
  #   depends_on:
  #     - kafka
  #   volumes:
  #     - ./web_service:/app
  #   networks:
  #     - kafka_net

  # mailer_service:
  #   build: ./mailer_service
  #   ports:
  #     - '3002:3000'
  #   environment:
  #     - KAFKA_BROKER=kafka:9092   # Внутренний адрес остается прежним
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - kafka
  #   volumes:
  #     - ./mailer_service:/app
  #   networks:
  #     - kafka_net

networks:
  kafka_net:
    driver: bridge

volumes:
  redis_data:
  clickhouse_data:
