source "https://rubygems.org"

gem "karafka", ">= 2.4.0"
gem "rack-cors", "~> 2.0.2"
gem "listen"
gem "stringio"
gem "rails", "~> 8.1.3"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "sprockets-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "activerecord-nulldb-adapter"
gem "dotenv-rails"
gem "rails-i18n"
gem "jsbundling-rails"
gem "clipboard-rails"
gem "httparty"
gem "circuitbox"
gem "tailwindcss-rails"
gem "jwt"
gem "redis"
gem "ostruct"
gem "sucker_punch"
gem "redis-session-store"
gem "click_house"
gem "webpacker"
gem "browser"
gem "multipart-post"
gem "faraday"
gem "faraday-multipart"
gem 'rest-client'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.0"
  gem "faker", "~> 2.0"
  gem "shoulda-matchers", "~> 5.0"
  gem "webmock", "~> 3.0"
  gem "vcr", "~> 6.0"
end

gem "cropper_rails", "~> 1.2"
