source "https://rubygems.org"


gem "karafka", ">= 2.4.0"
gem "waterdrop"
gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "sprockets-rails"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

gem "omniauth"
gem "omniauth-discord"
gem "omniauth-twitch"
gem "omniauth-rails_csrf_protection"
gem "omniauth-google-oauth2"
gem "yt"

gem "devise"
gem "devise-two-factor"
gem "rotp"
gem "rqrcode"
gem "rack-cors", "~> 2.0.2"
gem "dotenv-rails", "~> 3.1.8"
gem "redis-session-store"
gem "jwt"
gem "click_house"
gem "httparty"
gem 'multipart-post'

group :development, :test do
  gem "sqlite3", ">= 1.4"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "letter_opener"
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end

group :production do
  gem "mysql2"
  gem "rails_stdout_logging"
  gem "rack-attack"
end

gem "kaminari", "~> 1.2"

gem "active_storage_validations", "~> 3.0"

gem "mini_magick"
gem "image_processing"
