source "https://rubygems.org"


gem "karafka", ">= 2.4.0"
gem "waterdrop"
gem "rails", "~> 8.1.3"
gem "sprockets-rails"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

gem "omniauth", "~> 2.0"
gem "omniauth-discord"
gem "omniauth-twitch"
gem "omniauth-rails_csrf_protection", "~> 1.0"
gem "omniauth-google-oauth2"
gem "yt"

gem "devise"
gem "devise-two-factor"
gem "rotp"
gem "rqrcode"
gem "rack-cors", "~> 2.0.2"
gem "dotenv-rails", "~> 3.1.8"
gem "redis-session-store"
gem "jwt"
gem "click_house"
gem "httparty"
gem 'multipart-post'

group :development, :test do
  gem "sqlite3", ">= 1.4"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "letter_opener"
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.0"
  gem "faker", "~> 2.0"
  gem "shoulda-matchers", "~> 5.0"
  gem "webmock", "~> 3.0"
  gem "vcr", "~> 6.0"
  gem "database_cleaner-active_record", "~> 2.1"
end

group :production do
  gem "mysql2"
  gem "rails_stdout_logging"
  gem "rack-attack"
end

gem "kaminari", "~> 1.2"

gem "active_storage_validations", "~> 3.0"

gem "mini_magick"
gem "image_processing"

  gem "parallel_tests", "~> 5.7", :group => :test

  gem "spring", "~> 4.1.1"
