default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  secondary:
    <<: *default
    adapter: sqlite3
    database: storage/development.sqlite3

test:
    <<: *default
    adapter: sqlite3
    database: storage/test.sqlite3

production:
  <<: *default
  adapter: mysql2
  host: <%= ENV["DB_HOST"] %>
  port: 3306
  username: <%= ENV["WEB_DB_USERNAME"] %>
  password: "<%= ENV["WEB_DB_PASSWORD"] %>"
  database: <%= ENV["WEB_DB_DATABASE"] %>
  socket: false