default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    adapter: mysql2
    host: <%= ENV["DB_HOST"] %>
    username: <%= ENV["MC_DEV_DB_USERNAME"] %>
    password: "<%= ENV["MC_DEV_DB_PASSWORD"] %>"
    database: <%= ENV["MC_DEV_DB_DATABASE"] %>
    migrations_paths: db/development_migrate

production:
  primary:
    <<: *default
    adapter: mysql2
    host: <%= ENV["DB_HOST"] %>
    username: <%= ENV["MC_DB_USERNAME"] %>
    password: "<%= ENV["MC_DB_PASSWORD"] %>"
    database: <%= ENV["MC_DB_DATABASE"] %>
    migrations_paths: db/production_migrate
